###GET /

GET http://localhost:3000/

POST http://localhost:3000/auth/register
content-type: application/json
{
    "username":"gil@gmail.com",
    "password":"121212"
}

POST http://localhost:3000/auth/login
content-type: application/json
{
    "username":"gil@gmail.com",
    "password":"121212"
}